### ISSUE TITLE
On mac, box items coordinates are relative to screen, not window

### ISSUE THREAD

**Issue by brollin** [splondike/talon_ui_helper#1]
In the file `command_wizard.py` I have the line:
```py
        f'    bounding_rectangle = user.mouse_helper_calculate_relative_rect("{offsets}", "active_window")',
```
changed to
```py
        f'    bounding_rectangle = user.mouse_helper_calculate_relative_rect("{offsets}", "active_screen")',
```

in order for the box items feature to work. The feature "click a single image on the screen" didn't need any adjustment. Not sure why this is the case 🤔  I'm on a mac. Let me know if I can help further - I really love this tool!

**Comment by brollin** [comment]
Important addendum, I've just tested this with maximized windows only until just now. I'm sure as you would expect, it uses absolute positioning and no longer works to generate markers for the intended items. The issue seems to be that the coordinates generated for the talon script are absolute coordinates.

**Comment by splondike** [comment]
I fixed a bug with the blob detector a couple of weeks ago: f0d22d7be490a9cf9e39064481574c289979dc62 . Perhaps that's what is causing your issue (are you running the latest version)? My window manager makes things full screen by default which is why I didn't notice it until recently!

If that doesn't solve the problem let's narrow down the issue. The coordinates put into the offsets variable should be relative to the active window. Does it look like that's what's happening? You could try to define a box at the top left of the active window for example to see if that was the case, the first two numbers should be close to 0 0.

If that isn't the issue, could I then get you to do the following:

1. Open up the Talon REPL.
2. Run `actions.user.mouse_helper_calculate_relative_rect("1 1 -1 -1", "active_window")`.
3. Move the Talon REPL further to the right and down. Re-run the above line and check the first two numbers in the Rect are incremented.
4. Make the REPL a bit wider and higher. Re-run the above line and check the second and third numbers in the Rect are incremented.

Glad you like the system :).

**Comment by brollin** [comment]
Double checked and I have been working with the latest version of the repo.

Interestingly it seems that the coordinates are definitely absolute. With a finder window in the middle of the screen and focused, I do a command wizard shell and then box items, making a box in the top left hand corner of the finder window. The returned offsets are not close to 0, 0, and are very high numbers instead.

**Comment by splondike** [comment]
OK, for that to be the case I think the `ui.active_window().rect` function expression isn't giving me what I expect. My guess is it's picking up the wrong window, possibly the overlay itself.

Could I get you to edit the command_wizard.py file to add the following after line 98 (the `active_rectangle = ui.active_window().rect` line):

```python
    print("XXX", ui.active_window(), ui.active_window().rect, active_rectangle, result)
```

Then paste the "XXX" line from your log in here? I suspect it'll show something that isn't finder. But even if it does the two rects that get printed out should help me narrow down further.

**Comment by brollin** [comment]
I think your theory is correct given this output!
```
2022-02-07 18:57:10    IO XXX Window(app=App(pid=27417, "Talon"), title="") Rect(0.0, 0.0, 1920.0, 1080.0) Rect(0.0, 0.0, 1920.0, 1080.0) Rect(531, 206, 100, 30)
```
Hope there's a reasonable workaround.

**Comment by splondike** [comment]
OK cool. I've put up a branch `feature/fix-blob-detector-osx` that should fix that by saving the active window rectangle before the overlay is shown. Let me know if that fixes things and I'll merge it in :).

**Comment by brollin** [comment]
It's working! Thanks a ton for this fix 🎉

**Comment by splondike** [comment]
Excellent! I've merged that fix in to master.
